/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactRequest = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'inquiry' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getContactRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ContactRequest)],
      ['query'],
    ),
  'submitContactRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactRequest = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'inquiry' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactRequests' : IDL.Func(
        [],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getContactRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ContactRequest)],
        ['query'],
      ),
    'submitContactRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };